list1 = new Array();
list1.push("L'excellence ");
list1.push("L'intervention ");
list1.push("L'objectif ");
list1.push("Le diagnostic ");
list1.push("L'expérimentation ");
list1.push("La formation ");
list1.push("L'évaluation ");
list1.push("La finalité ");
list1.push("L'expression ");
list1.push("Le management ");
list1.push("La méthode ");
list1.push("Le vécu ");
list1.push("Le recadrage ");

list2 = new Array();
list2.push("renforce ");
list2.push("mobilise ");
list2.push("révèle ");
list2.push("stimule ");
list2.push("modifie ");
list2.push("clarifie ");
list2.push("renouvelle ");
list2.push("identifie ");
list2.push("perfectionne ");
list2.push("développe ");
list2.push("dynamise ");
list2.push("programme ");
list2.push("ponctue ");

list3 = new Array();
list3.push("les facteurs ");
list3.push("les processus ");
list3.push("les paramètres ");
list3.push("les changements ");
list3.push("les concepts ");
list3.push("les savoir-faire ");
list3.push("les problèmes ");
list3.push("les indicateurs ");
list3.push("les résultats ");
list3.push("les effets ");
list3.push("les blocages ");
list3.push("les besoins ");
list3.push("les paradoxes ");

list4 = new Array();
list4.push("institutionnels ");
list4.push("organisationnels ");
list4.push("qualitatifs ");
list4.push("analytiques ");
list4.push("caractéristiques ");
list4.push("motivationnels ");
list4.push("pédagogiques ");
list4.push("représentatifs ");
list4.push("participatifs ");
list4.push("cumulatifs ");
list4.push("stratégiques ");
list4.push("neuro-linguistiques ");
list4.push("systémiques ");

list5 = new Array();
list5.push("de la performance.");
list5.push("du dispositif.");
list5.push("de l'entreprise.");
list5.push("du groupe.");
list5.push("du projet.");
list5.push("des bénéficiaires.");
list5.push("de la hiérarchie.");
list5.push("des pratiques.");
list5.push("de la démarche.");
list5.push("des acteurs.");
list5.push("de la problématique.");
list5.push("des structures.");
list5.push("du méta-contexte.");

var s1 = list1[Math.floor(Math.random() * 13)];
var s2 = list2[Math.floor(Math.random() * 13)];
var s3 = list3[Math.floor(Math.random() * 13)];
var s4 = list4[Math.floor(Math.random() * 13)];
var s5 = list5[Math.floor(Math.random() * 13)];

document.write(s1 + s2 + s3 + s4 + s5);
